### PR TITLE
Fixed some stuff for Capybara 0.4.0 compatibility

### PR DESCRIPTION
**Pull request by jnicklas**
I switched the gem to use bundler and a gemspec for development, this makes it very easy for others to set up a dev environment. I've found on my own projects that this has made development much easier.

I also fixed two failures agains Capybara 0.4.0. We now have only two remaining, one where the incorrect header is reported, that's not really a problem, and more that the Capybara test suite isn't formulating the test very well, this probably needs to be fixed in Capybara itself, not in capybara-envjs. The other is for a certain type of fill_in instructions, where it doesn't work, I can't figure that one out.

### CODE REVIEW

**Comment by smparkes** [comment]
Thanks! Merged.

The fill_in issue is, I think, a difference in the order of the node sets returned by the different xpath engines. The fill_in spec "Street" matches multiple elements on the page. The action selects the first matching element.

However, as far as I can tell, the result of doing a union results in an unordered node set. See http://lists.xml.org/archives/xml-dev/200410/msg00005.html and http://lists.xml.org/archives/xml-dev/200410/msg00006.html.

I could probably sort the list into document order but I don't know if I should.

**Comment by jnicklas** [comment]
The test probably shouldn't be so ambiguous. We'll see about getting this fixed in Capybara. Afaics that leaves no issues in capybara-envjs now, those failing tests are really problems with Capybara's test suite. Could you do a gem release?

**Comment by smparkes** [comment]
Just wanted to see what you thought about the ordering before I did.

**Comment by jnicklas** [comment]
Well, it does sound like the order is undefined, which means that Capybara-envjs is free to choose whatever order it wants. I personally find document order more intuitive, but the Capybara specs shouldn't rely on behaviour that is not specified.

**Comment by smparkes** [comment]
In the xpath engine that env-js uses, I think it only comes up when merging node sets, which I think mostly occurs when doing unions. I'm not terribly surprised since it's probably doing multiple walks and just concatenating the results. Hopefully it's removing dups.

It does look like XPath 2 requires document order: http://www.w3.org/TR/xpath20/#combining_seq

**Pull request closed without merging**
